### ISSUE TITLE
Chrono Cross freezes while consulting Char's Status

### ISSUE THREAD

**Issue by caiot5** [libretro/swanstation#103]
With the most recent iteration of SwanStation core, I get a total freeze when trying to display the character's status. 
It doesn't matter which character, it doesn't matter which GPU core (vulkan, GL or software mode) and it doesn't matter also if the CPU emulation is set to interpreter or recompiler.
Also when the first FMV plays (the one showing the Square logo) I can listen to a little beep and the main FMV plays one side mono only.
That doesn't happen with any other core, just with swan station and I couldn't find any fix for that.

**Comment by yotengodormir** [comment]
Just ran into this issue as well and found this thread. 
Can confirm, same issue: going to Status screen results in black screen and game freeze. 
Tried different options, couldn't fix.

**Comment by RyanBram** [comment]
Commits made between versions 1.14.0 and 1.15.0 are likely the cause. The bug started to occur in version 1.15.0 and Chrono Cross is still running normally in 1.14.0. You can try the core at version 1.14.0 for a temporary solution, but unfortunately on Android we don't have the option to revert back to the old core.

https://buildbot.libretro.com/stable/

**Comment by KamiLordus** [comment]
I confirm that in the core version (f2e335b) the menu/stats works properly. One of the later fixes broke something. I tested versions of the game in chd and bin/cue formats, using different options, and each time I had the same problem as in post 1.

Win 11 Pro
Retroarch 1.18
Swanstation latest

**Comment by DarthMew** [comment]
Fixed via https://github.com/libretro/swanstation/commit/929958a1acaa075e32e108118b550e0449540cb6

**Comment by caiot5** [comment]
I'm still having the same issue, been updating the retroarch cores for a while hoping that it will eventually get merged but then nothing. Maybe I'm missing something?
